/*
 * This file was generated by generate_typesystem.py.
 */
#ifndef __RS_MASKRCNN_ALL_TYPES_H__
#define __RS_MASKRCNN_ALL_TYPES_H__

#include <rs_maskrcnn/types/type_definitions.h>


#endif /* __RS_MASKRCNN_ALL_TYPES_H__ */
